version: '3'

services:
  aplicacao:
    container_name: quarkus_app
    build: 
      context: ./
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://mysqldb:3306/projeto_financeiro?allowPublicKeyRetrieval=true
      - QUARKUS_DATASOURCE_USERNAME=projeto_financeiro
      - QUARKUS_DATASOURCE_PASSWORD=123456
      - QUARKUS_FLYWAY_MIGRATE_AT_START=true   
    depends_on:
      db :
        condition : service_healthy
  db:
    image: mysql:9.0
    container_name: mysqldb
    healthcheck:
      test: ['CMD','mysqladmin','ping','-h','localhost']
      interval: 20s
      timeout: 10s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: projeto_financeiro
      MYSQL_USER: projeto_financeiro
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
    

    