quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/ppfsiv_quarkus?allowPublicKeyRetrieval=true
# quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/ppfsiv?allowPublicKeyRetrieval=true
quarkus.datasource.username=root
quarkus.datasource.password=

quarkus.flyway.enabled=true
quarkus.flyway.migrate-at-start=true
quarkus.datasource.db-version=5.5.5

quarkus.test.continuous-testing=disabled